acme_store_homepage:
    path:     /
    defaults: { _controller: AcmeStoreBundle:Default:index }
acme_store_insecion:
    path:     /insercion
    defaults: { _controller: AcmeStoreBundle:Default:insercion }
